export interface InitiatePaymentInput {
  /** Amount in the smallest currency unit (kobo for NGN, pesewas for GHS) */
  amount: number;
  email: string;
  /** Unique reference generated by the caller */
  reference: string;
  currency?: string;
  /** URL Paystack (or other provider) redirects to after payment */
  callbackUrl?: string;
  metadata?: Record<string, unknown>;
}

export interface PaymentInitiationResult {
  reference: string;
  /** URL to redirect the user to for payment */
  checkoutUrl: string;
}

export interface PaymentVerificationResult {
  reference: string;
  status: 'success' | 'failed' | 'pending';
  /** Amount in smallest currency unit */
  amount: number;
  email: string;
  metadata?: Record<string, unknown>;
}

export interface WebhookEvent {
  /** Provider-specific event name, e.g. "charge.success" */
  event: string;
  reference: string;
  status: 'success' | 'failed';
  /** Amount in smallest currency unit */
  amount: number;
  email: string;
  metadata?: Record<string, unknown>;
}

/**
 * Contract every payment provider must satisfy.
 * To add a new provider: implement this interface, then update PaymentModule.
 */
export interface IPaymentProvider {
  initiatePayment(input: InitiatePaymentInput): Promise<PaymentInitiationResult>;
  verifyPayment(reference: string): Promise<PaymentVerificationResult>;
  /** Returns true if the signature is valid for the given raw body */
  validateWebhookSignature(rawBody: Buffer, signature: string): boolean;
  parseWebhookEvent(payload: Record<string, unknown>): WebhookEvent;
}
